import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(process.cwd(), '.env') });

export default {
  PORT: process.env.PORT,
  DATABASE_URL: process.env.DATABASE_URL,
  BETTER_AUTH_URL:process.env.BETTER_AUTH_URL,
  BETTER_AUTH_SECRET:process.env.BETTER_AUTH_SECRET,
  ACCESS_TOKEN_SECRET:process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET:process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN:process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN:process.env.REFRESH_TOKEN_EXPIRES_IN,
  BETTER_AUTH_SESSION_TOKEN_EXPIRES_IN:process.env.BETTER_AUTH_SESSION_TOKEN_EXPIRES_IN,
  BETTER_AUTH_SESSION_TOKEN_UPDATE_AGE:process.env.BETTER_AUTH_SESSION_TOKEN_UPDATE_AGE,
  FRONTEND_URL: process.env.FRONTEND_URL
};
